.github/workflows/core-test.yml, README.md, includes/minishell.h
This is a test for GitHub actions with PR trigger
=> doc: update doc to test actions

.github/workflows/core-test.yml
- add new parameter in core.yml for GitHub actions test command with input
=> feat: add command parameter

includes/minishell.h, srcs/commands.c, srcs/main.c
Create a condition to check command name equal exit and than break loop
=> feat: #45 check command equal exit

libft/ft_strpbrk.c, libft/ft_strtok.c, libft/libft.h
This PR implements two new functions in Libft
- ft_strtok (core for tokens)
char	*ft_strtok(char *str, const char *delim, int tigger)
- ft_strpbrk (auxiliar for strtok)
char	*ft_strpbrk(const char *str, const char *delim)
=> feat: #44 add ft_strtok in libft

Makefile, includes/minishell.h, srcs/main.c, srcs/signals/signals.c
This code implements handlers to SIGINT, SIGQUIT and SIGTERM.
*handler*: This function is called when the process recive an signal interruption SIGINT. It\`s happens when Ctrl+C is pressed on command line. It\`s returns an new line.
*signal_handler*: This functiction is called when the process recive an signal SIGQUIT or SIGTERM.
- SIGQUIT in most cases when Ctrl+\ is pressed in the command line. does nothing.
- SIGTERM  is the default termination signal that can be sent to a process to request that it terminate. When this signal is received, the function calls exit(0) to terminate the program.
*signals_handler*: This function sets the handlers for the SIGINT, SIGQUIT, and SIGTERM signals using the signal function. This function accepts two arguments: the number of the signal whose want …
=> Signals base

includes/minishell.h, includes/structs.h, srcs/commands.c, srcs/commands/echo.c, srcs/commands/exit.c, srcs/commands/pwd.c, srcs/envs.c, srcs/main.c
=> 60 echo command use envs

srcs/commands/pwd.c
No significant changes made, remove print args from pwd.
=> fix: adjust result to similar original pwd

.github/workflows/cmd-echo-test.yml, .github/workflows/cmd-exit-test.yml, srcs/commands/echo.c, srcs/input.c
- No core minishell are edited, only tests in github actions
- write some test for echo and adjust name of exit command test
=> 32 write tests for commands echo

srcs/commands/echo.c, srcs/input.c
- Edited echo.c -> print $?
- Edited input.c -> command not found return exit code 127
=> feat: #68 implement print exit code

Makefile, includes/minishell.h, srcs/input.c, srcs/main.c, srcs/parser/syntax_analysis.c, srcs/parser/token_analysis.c
create engine to use tokens and syntax but without business decision
=> feat: token and syntax analises

Makefile, srcs/commands/unset.c
This pull is about productivity, I have implementing a rule for valgrind to helps to call the tool
=> Create a rule to valgring in Makefile

srcs/input.c
**What happend?**
- Leak when press enter without set command
**What expected?**
- No leak
=> fix: #78 leak when empty command

srcs/redirects/ft_pipe.c
This pull has in process. Needs to test until!!! Be carful!
=> feat(redirects): Create a redirect folder

Makefile, includes/minishell.h, srcs/input.c, srcs/main.c, srcs/parser/build_struct_to_exec.c, srcs/parser/syntax_analysis.c, srcs/parser/token_analysis.c
Add new struct cmds->cmd_list, each node it is a command like PIPE, DGREAT, GREAT, DLESS, LESS, or WORD for phrases
=> 71 engine token and syntax grammatic

srcs/parser/build_struct_to_exec.c
=> fix: ld token fail

srcs/parser/build_struct_to_exec.c, srcs/parser/token_analysis.c
remove leaks when create a new node
=> fix: remove leaks

srcs/builtins/exit.c, srcs/commands/path.c, srcs/main.c
=> fix: solve norminette

Makefile, includes/minishell.h, srcs/commands/commands.c, srcs/commands/exec_builtin_cmd.c, srcs/commands/exec_external_cmd.c, srcs/commands/path.c, srcs/commands/type_commands.c, srcs/main.c
- Implement `void	exec_builtin(t_cmds *cmds)` 
- all leaks solved
- fork implemented
- waitpid waiting fork finish
- add exit in children
- free in all status
=> 9 implement pipes

includes/minishell.h, srcs/builtins/echo.c, srcs/builtins/export.c, srcs/commands/path.c, srcs/minishell_utils.c
- make -n checked
- /bin/ls working
=> feat: make -n and /bin/ls

Makefile, includes/minishell.h, srcs/builtins/echo.c, srcs/builtins/echo_utils.c, srcs/read_keyboard/input.c
- leaks -> OK
- ${PWD -> OK
- $PWD -> OK
- ${PWD} -> OK
=> feat: solve all problem identified in echo

Makefile
This pull request improves the how we call the files in Makefiles. Now isn`t necessary to update Makefile when is created an new file. There is an rule whose read and put the directories and subs  in a variable `rwildcard`.
=> feat(Makefile): including valgrid rule and otmize

.gitignore, Makefile, includes/minishell.h, srcs/read_keyboard/input.c
This branch fix an leak on echo when you type exit after execute the command echo:
Fix:
=> Patch fixing leak space echo

srcs/builtins/export.c, srcs/minishell_utils.c, unit_tests.sh
**When run:**
export
unset
export NAME="Antonio"
export
**Solved:** 
-       if (cmds->envs == NULL)
+       if (cmds->envs == NULL && cmds->current->full_args == NULL)
return (1);
=> fix: set to ingnore null when has args

includes/minishell.h, srcs/commands/exec_external.c, srcs/commands/file.c, srcs/commands/nodes.c, srcs/commands/strategy.c, srcs/pipes/pipes.c
=> feat: delivery someting >> > and <

srcs/builtins/echo.c
solved echo "a b"
return only a b
=> bug: correct position in array

includes/minishell.h, srcs/commands/here_doc.c, srcs/commands/strategy.c, srcs/commands/strategy_set_utils.c
solved problem with EOF output
=> fix: solve fd correct output

srcs/builtins/cd.c, srcs/parser/interpreter.c
=> 148 remove print with going to

srcs/builtins/cd.c, srcs/commands/exec_external.c
fixed bug/178-bug-uninitialized-vars
=> fix: uninitialized vars
